New ontokit tool (#906)
# 

The new ontokit tool backbone setup. 

This is included in master even though it is expected to change substantially in the near future because
the current version is already in use by a few repos (domain-atomistic and domain-magnetic-materials).

The two sub-commands that have been added are:
ontokit setup : sets up the ontology repo with github workflows (which use ontokit docs)
ontokit docs : runs the creation of reference documentation.

## Type of change
<!-- Put an `x` in the box that applies. -->
- [ ] Bug fix.
- [ ] New feature.
- [ ] Documentation update.
- [ ] Test update.

## Checklist
<!-- Put an `x` in the boxes that apply. You can also fill these out
after creating the PR. -->

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit
testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and
if so is this documented?

## Comments
<!-- Additional comments here, including clarifications on checklist if
applicable. -->

---------

Co-authored-by: Francesca L. Bleken <48128015+francescalb@users.noreply.github.com>
Co-authored-by: Francesca.L.Bleken@sintef.no <francesca.l.bleken@sintef.no>

diff --git a/.github/workflows/ci_workflow.yml b/.github/workflows/ci_workflow.yml
--- a/.github/workflows/ci_workflow.yml
+++ b/.github/workflows/ci_workflow.yml
@@ -13,7 +13,7 @@ jobs:
     uses: SINTEF/ci-cd/.github/workflows/ci_tests.yml@v2.9.2
     with:
       # General
-      install_extras: "[dev,docs,excel,ontodoc]"
+      install_extras: "[dev,docs,excel,ontodoc,ontokit]"
 
       # pre-commit
       run_pre-commit: true
@@ -126,7 +126,9 @@ jobs:
           --doctest-modules \
           --ignore tests/test_graphviz \
           --ignore tests/test_excelparser \
-          --ignore tests/test_java | tee result.log
+          --ignore tests/test_java \
+          --ignore ontopy/ontokit/docs.py \
+          --ignore tests/test_ontodoc_rst.py | tee result.log
         if grep -q "SKIPPED" result.log; then
           echo "❌ Skipped tests detected, failing build"
           exit 1
@@ -200,13 +202,39 @@ jobs:
           --cov=ontopy --cov=emmopy --cov-append \
           --cov-report=term --cov-report= \
           --doctest-modules \
-          tests/test_graphviz | tee result_graphviz.log
+          tests/test_graphviz \
+          tests/test_ontodoc_rst.py | tee result_graphviz.log
 
         # Fail if any Graphviz tests got skipped
         if grep -q "SKIPPED" result_graphviz.log; then
           echo "❌ Skipped tests detected in Graphviz phase, failing build"
           exit 1
         fi
+
+    - name: Round 5 – ontokit tests (Python 3.12+)
+      if: matrix.python-version >= '3.12'
+      run: |
+        set -euo pipefail
+
+        # Install Python deps required by ontokit tests
+        pip install -U -e .[ontokit]
+
+        # Run ONLY the ontokit tests
+        #pytest -rA \
+        #  --cov=ontopy --cov=emmopy --cov-append \
+        #  --cov-report=term --cov-report= \
+        #  --doctest-modules \
+        #  ontopy/ontokit \
+        #  tests/tools/ontokit | tee result_ontokit.log
+
+        # Fail if any ontokit tests got skipped
+        #if grep -q "SKIPPED" result_ontokit.log; then
+        #  echo "❌ Skipped tests detected in ontokit phase, failing build"
+        #  exit 1
+        #fi
+
+
+
 
     - name: Generate XML once
       run: |
