Created functionality for creating and using ontokit conf (#935)
# Description
ontokit now uses an .ontokit_conf.yml file for variables that are used
in more subcommands.

With ontokit setup this file is now created if it does not already
exist, otherwise updated with the missing variables.
If it already exists it will not be overwritten. The workflow files, use
this configuration file as does ontokit docs.

diff --git a/.github/workflows/ci_workflow.yml b/.github/workflows/ci_workflow.yml
--- a/.github/workflows/ci_workflow.yml
+++ b/.github/workflows/ci_workflow.yml
@@ -220,18 +220,18 @@ jobs:
         pip install -U -e .[ontokit]
 
         # Run ONLY the ontokit tests
-        #pytest -rA \
-        #  --cov=ontopy --cov=emmopy --cov-append \
-        #  --cov-report=term --cov-report= \
-        #  --doctest-modules \
-        #  ontopy/ontokit \
-        #  tests/tools/ontokit | tee result_ontokit.log
+        pytest -rA \
+          --cov=ontopy --cov=emmopy --cov-append \
+          --cov-report=term --cov-report= \
+          --doctest-modules \
+          ontopy/ontokit \
+          tests/tools/ontokit | tee result_ontokit.log
 
         # Fail if any ontokit tests got skipped
-        #if grep -q "SKIPPED" result_ontokit.log; then
-        #  echo "❌ Skipped tests detected in ontokit phase, failing build"
-        #  exit 1
-        #fi
+        if grep -q "SKIPPED" result_ontokit.log; then
+          echo "❌ Skipped tests detected in ontokit phase, failing build"
+          exit 1
+        fi
 
 
 
